### ISSUE TITLE
Unable to upload GPX files via python's requests.put - was working until commit: 00f689e

### ISSUE THREAD

**Issue by githubhacs** [open-wanderer/wanderer#132]
https://github.com/Flomp/wanderer/commit/00f689ec2fabe3629731cdb51a1967a793a5440b#diff-6510e47a0169939f753bf0c283ce507b366717d068a8871bcf531219298208ecR35

hi - this change to a multipart form broke my existing Python code for uploading GPX files.

this used to work:

```
api_endpoint = API_URL + 'trail/upload/'

gpx_filedata = open(gpx_file, "rb").read()

```

original put for uploading the GPX:
```
session.put(api_endpoint , headers={'Content-Type': 'application/gpx+xml'}, data=gpx_filedata)
```

I've looked at your CURL commands in the cron.sh but I'm failing to get it working again in python; obviously my skill level isn't good enough!

```
upload_put_data = {
   'file': gpx_filedata
 }

upload_new_trail = session.put(api_endpoint , data=upload_put_data)
```

Any ideas on what I'm doing wrong or whether this should be a POST instead of the previous PUT? 

Thanks.

From the wanderer logs:
```
wanderer-web     | TypeError: data.get(...).arrayBuffer is not a function
wanderer-web     |     at PUT (file:///app/build/server/chunks/_server.ts-Tk1jQCRl.js:2994:47)
wanderer-web     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wanderer-web     |     at async render_endpoint (file:///app/build/server/index.js:1487:20)
wanderer-web     |     at async resolve2 (file:///app/build/server/index.js:4004:22)
wanderer-web     |     at async auth (file:///app/build/server/chunks/hooks.server-248u8dmy.js:118:20)
wanderer-web     |     at async respond (file:///app/build/server/index.js:3898:22)
wanderer-web     |     at async Array.ssr (file:///app/build/handler.js:1243:3)
wanderer-web     | Error: HTTP error status codes must be between 400 and 599 — undefined is invalid
wanderer-web     |     at error (file:///app/build/server/chunks/index-oXbhYwP7.js:54:11)
wanderer-web     |     at PUT (file:///app/build/server/chunks/_server.ts-Tk1jQCRl.js:3044:11)
wanderer-web     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wanderer-web     |     at async render_endpoint (file:///app/build/server/index.js:1487:20)
wanderer-web     |     at async resolve2 (file:///app/build/server/index.js:4004:22)
wanderer-web     |     at async auth (file:///app/build/server/chunks/hooks.server-248u8dmy.js:118:20)
wanderer-web     |     at async respond (file:///app/build/server/index.js:3898:22)
wanderer-web     |     at async Array.ssr (file:///app/build/handler.js:1243:3)
```

**Comment by githubhacs** [comment]
I've rewritten the upload portion in golang.
